### ISSUE TITLE
Missing Links: Project 1

### ISSUE THREAD

**Issue by gavinn2** [uci-ieee/ops-webpages-2023-2024#11]
Soldering concepts does not have link yet

![Screenshot 2023-07-25  @220127](https://github.com/uci-ieee/ops-webpages-2023-2024/assets/140114907/597a75dd-2fa7-474e-9fee-2c23ef235219)

**Comment by vu-dylan** [comment]
(the actual workshop link needs to be provided)

**Comment by leavenember** [comment]
@gavinn2 @vu-dylan please put last year's soldering workshop slides here as a placeholder

**Comment by bcbielecki** [comment]
Resolved!
