### ISSUE TITLE
Missing Links: Project 2

### ISSUE THREAD

**Issue by deonn1** [uci-ieee/ops-webpages-2023-2024#12]
![Screenshot 2023-07-29 202401](https://github.com/uci-ieee/ops-webpages-2023-2024/assets/140115814/0ccaf2d6-5540-47a1-ae67-fae01b2afd6f)
![Screenshot 2023-07-29 202411](https://github.com/uci-ieee/ops-webpages-2023-2024/assets/140115814/ab78c029-90e0-412e-9063-900bb7895744)

**Comment by leavenember** [comment]
@deonn1 Can you put the last year's soldering workshop slides in for now?

**Comment by bcbielecki** [comment]
Resolved!
