### ISSUE TITLE
Capstone Rover Project Page

### ISSUE THREAD

**Issue by bcbielecki** [uci-ieee/ops-webpages-2023-2024#139]
## Description

You will adapt the Capstone Project [Specifications Document](https://docs.google.com/document/d/1lYzfvpiHavSsT48ziEXrPI_iIuArOqxdB3gDLh-b00I/edit) to a webpage

## Requirements
- [ ] Create all changes in a new branch
- [ ] Create a new .HTML file, using `project_6.html` as the baseplate code.
- [ ] Transfer all text
   - [ ] Make sure all hyperlinks work
   - [ ] Upload all datasheets and link them to the parts in the parts lists (Arduino Nano, ICs, etc.)
- [ ] Transfer all images (ensure they are high-resolution)
- [ ] Check for responsiveness on the following media sizes:
   - [ ] Mobile (iPhone SE)
   - [ ] Desktop: 600px < vw < 996px
   - [ ] Desktop: 996px < vw > 1200px
   - [ ] Desktop: vw > 1200px
- [ ] Open a PR for the branch and assign reviewers

## Notes

- Task Lead: @dylanvu

**Comment by dylanvu** [comment]
resolved
