### ISSUE TITLE
question: are we supposed to check in compiled scss to repository

### ISSUE THREAD

**Issue by vu-dylan** [uci-ieee/ops-webpages-2023-2024#16]
It seems a bit weird that we check in the compiled CSS in our repository. I'd imagine this could cause more merge conflicts down the road especially if multiple people modify the scss?

I've never used scss before, but it would make sense to me that we'd compile CSS locally (or before deployment), similar to how other tools like TypeScript, frameworks that involve building webpages like React and Next.js, and other languages like C++ don't usually check in the output files? What is the standard practice with scss?

The idea is that given the source files (aka, the scss files), we can easily regenerate the CSS files at will. This keeps our repo lighter weight, reduces the size of commits and pull requests, likely avoids potential merge conflicts, etc.

If we no longer check stuff in, the website workflow needs to have a building step most likely. The workflow file is here: https://github.com/uci-ieee/ieee-website-2023-2024/blob/main/.github/workflows/deploy_to_prod.yml

**Comment by leavenember** [comment]
Both repos now have build steps in their workflows.
.gitignore is also updated
