### ISSUE TITLE
weird spacing in between "RGB LED " and "Using it with Arduino" headers

### ISSUE THREAD

**Issue by gavinn2** [uci-ieee/ops-webpages-2023-2024#32]
![image](https://github.com/uci-ieee/ops-webpages-2023-2024/assets/140114907/7fa17e2d-e3c8-45f5-9148-5359302f251a)

**Comment by vu-dylan** [comment]
it was an issue with headers and p, I put the contents inside of a div and let the CSS fix itself. Addressed in the PR that will be associated with https://github.com/uci-ieee/ops-webpages-2023-2024/issues/27

**Comment by vu-dylan** [comment]
This commit right here: https://github.com/uci-ieee/ops-webpages-2023-2024/commit/3f3de89bc618bd716b879ac958bb3e7667c12762
