### ISSUE TITLE
Broken Responsive Container on Projects Page

### ISSUE THREAD

**Issue by bcbielecki** [uci-ieee/ops-webpages-2023-2024#4]
When the project page is reduced in width, eventually a container fails to breakdown and instead extends beyond the viewport width.

**Comment by bcbielecki** [comment]
@vu-dylan I'm going to throw this bug at you to solve with Gavin as you guys work on Project 1. 

It should be an easy fix (a matter of changing a class on the HTML doc... maybe a small change to the custom sass. When you find the issue, please open a new branch where you fix it on **project_template.html**. Make sure to add the fix to your current branch as well.

**Comment by bcbielecki** [comment]
I suspect it's the container with the update information (the grey box) or its parent container. Likely, the solution is to set the parent to flex column on breakdown. The classes you would add to that container might be something like  `flex-row-lg`  and `flex-column-sm`. Not sure.

![Image](https://github.com/uci-ieee/ops-webpages-2023-2024/assets/45702229/121ed242-be1c-48b9-acc9-d9e9d406f0ef)

**Comment by vu-dylan** [comment]
Depends on https://github.com/uci-ieee/ops-webpages-2023-2024/issues/14 most likely
