### ISSUE TITLE
fix awkward space in card component in responsive view

### ISSUE THREAD

**Issue by dylanvu** [uci-ieee/ops-webpages-2023-2024#51]
![image](https://github.com/uci-ieee/ops-webpages-2023-2024/assets/75911565/06b240b5-1483-4bed-b7e9-87044c01b3d3)

There seems to be an odd large space between the end of the content of the card text and the button when viewing the cards vertically. Pictured is an example.

Goal: make the white space between the end of the text and the buttons for slides and video be significantly smaller. It should be attached to the end of the text.

**Comment by Sky-De** [comment]
@dylanvu hi, i would like to work on this
Please provide information about what exactly you want and then assign this to me
Thanks

**Comment by bcbielecki** [comment]
Resolved! A recent PR changed the sizing of the cards.
