### ISSUE TITLE
fix oddly sized collapsible on mobile

### ISSUE THREAD

**Issue by dylanvu** [uci-ieee/ops-webpages-2023-2024#56]
Portrait:
![image](https://github.com/uci-ieee/ops-webpages-2023-2024/assets/75911565/8e6b0ed8-fb98-41d5-af62-0260dff03fdb)

![image](https://github.com/uci-ieee/ops-webpages-2023-2024/assets/75911565/4f4c2a0c-d94a-471e-b05a-f69a4926e109)

Landscape:
![image](https://github.com/uci-ieee/ops-webpages-2023-2024/assets/75911565/07ce07fb-6be5-4536-8b4c-44590d0cdad1)

The size of the button to show/hide the collapsible should not be big

**Comment by bcbielecki** [comment]
Fixed by #116
