### ISSUE TITLE
Project 2 Responsiveness Bug on Mobile

### ISSUE THREAD

**Issue by bcbielecki** [uci-ieee/ops-webpages-2023-2024#73]
Images exceed size of viewport on the Project 2 Page on mobile devices

![image](https://github.com/uci-ieee/ops-webpages-2023-2024/assets/45702229/a68a644c-f398-4729-b381-6e948c1dc479)
![image](https://github.com/uci-ieee/ops-webpages-2023-2024/assets/45702229/fdaa67c4-b3f3-47ec-a340-849545978406)

**Comment by dylanvu** [comment]
my initial thought is that it could be related to this issue that we fixed: https://github.com/uci-ieee/ops-webpages-2023-2024/issues/4

but our changes weren't updated in this project

**Comment by dylanvu** [comment]
yep, seems like it was
