### ISSUE TITLE
Browser Caching Prevents Client-Side Website Updates

### ISSUE THREAD

**Issue by bcbielecki** [uci-ieee/ops-webpages-2023-2024#77]
As shown below, certain browsers like Chrome cache css and js files instead of GETing the most recent files from the server.
This poses a major issue as we put up weekly updates to the site that students need to see immediately on their end.

![image](https://github.com/uci-ieee/ops-webpages-2023-2024/assets/45702229/95c46eef-9b78-480f-bd64-41a493b55398)

An inelegant solution we have is to use a special meta tag on all projects pages OR a query param on the js scripts for the pages with js-based footers and headers.  This would force the browser to fetch the newest files, but I think it will require a lot of upkeep for us to maintain long-term as we add more files. It's better than nothing though.
 
https://stackoverflow.com/questions/30764510/website-html-doesnt-update-for-users-because-of-cache

**Comment by dylanvu** [comment]
I am doing some investigation on industry standards here, and this is what someone mentioned: hashing our js files

https://github.com/mkdocs/mkdocs/issues/1979#issuecomment-830978467

I'm looking to see if we can automate hashing of our js files through our github workflows maybe

**Comment by dylanvu** [comment]
I think that I will implement some sort of hashing and attach it to our current workflow:
https://javascript.plainenglish.io/what-is-cache-busting-55366b3ac022

**Comment by dylanvu** [comment]
![image](https://github.com/uci-ieee/ops-webpages-2023-2024/assets/75911565/a4d81e37-7ab1-462e-ad67-df9afed8e78c)
seems to have worked
