### ISSUE TITLE
Add to Project 2 Parts List

### ISSUE THREAD

**Issue by bcbielecki** [uci-ieee/ops-webpages-2023-2024#80]
![image](https://github.com/uci-ieee/ops-webpages-2023-2024/assets/45702229/b5b6c920-d158-431d-a436-979c3cc68962)

Add the following to the parts list:

"Piano PCB or Perfboard"

The terms "Piano PCB" and "Perfboard" should display tooltips that show what the parts look like.

**Comment by dylanvu** [comment]
resolved
