### ISSUE TITLE
Large Margin on Right Side of Main Body in Projects Pages

### ISSUE THREAD

**Issue by bcbielecki** [uci-ieee/ops-webpages-2023-2024#85]
A margin on the right side of the main body in all three project pages should be reduced to the same size as the left in these projects.

![image](https://github.com/uci-ieee/ops-webpages-2023-2024/assets/45702229/6b08f4b4-8676-4c50-b011-c82b0babfa73)

**Comment by dylanvu** [comment]
did some research on why it was still behaving weirdly after adding `margin-right: auto` and `margin-left: auto`

https://forum.freecodecamp.org/t/why-margin-doesnt-work/346366/2

turns out we need to make the main an inline-block
