### ISSUE TITLE
Change the Roboto Font CDN

### ISSUE THREAD

**Issue by bcbielecki** [uci-ieee/ops-webpages-2023-2024#87]
Please change the href of the robot font link on each page to "https://fonts.googleapis.com/css2?family=Roboto"

Before:
![image](https://github.com/uci-ieee/ops-webpages-2023-2024/assets/45702229/426fc7f8-62c2-407c-951d-184b6a825c5a)

After:
![image](https://github.com/uci-ieee/ops-webpages-2023-2024/assets/45702229/6fd8b4c2-735b-4907-bf1a-6d8da854f392)

**Comment by dylanvu** [comment]
low key I'll just implement this in #55 ...?

**Comment by dylanvu** [comment]
implemented in #55
