### ISSUE TITLE
JS Scripts Not Hashed

### ISSUE THREAD

**Issue by bcbielecki** [uci-ieee/ops-webpages-2023-2024#95]
Not all JS scripts appear to be hashed. This could present an issue when footer.js, card.js, etc. are updated

![image](https://github.com/uci-ieee/ops-webpages-2023-2024/assets/45702229/0509879a-0472-4e8e-9f14-961a6a79f739)

**Comment by dylanvu** [comment]
current status:
1. my script is finding the ops_footer.js file and generating a hash for it
2. my script is locating the `workshop.html` file in the snippet

might be an issue with how I'm replacing

**Comment by dylanvu** [comment]
![image](https://github.com/uci-ieee/ops-webpages-2023-2024/assets/75911565/31e5188f-ad3f-4a09-9c18-e663d1b6bc81)
![image](https://github.com/uci-ieee/ops-webpages-2023-2024/assets/75911565/3e242acf-1388-4135-a70e-01516d2bb1f8)
Seems like it might work

I ended up just only writing the new html file at the end once
