### ISSUE TITLE
Project 6 Webpage

### ISSUE THREAD

**Issue by bcbielecki** [uci-ieee/ops-webpages-2023-2024#98]
## Overview

- **Project Title**: Weather Station
- **Topics**: Communication, I2C Protocol, SPI Protocol
- **Details**: Build a weather station that wirelessly transmits temperature and humidity data to an indoor display. See [Syllabus](https://ieee.ics.uci.edu/ops/assets/pdfs/ops_syllabus.pdf)

You will adapt the Project 6 [Specifications Document](https://docs.google.com/document/d/1sQDIYkW2RQRlIWTK5nZV0llGbNAHBotc-vfrEC-mJg8/edit) to a webpage

## Requirements
- [ ] Create all changes in a new branch
- [ ] Create a new .HTML file, using `project_template.html` as the baseplate code.
- [ ] Transfer all text
   - [ ] Make sure all hyperlinks work
   - [ ] Upload all datasheets and link them to the parts in the parts lists (Arduino Nano, ICs, etc.)
- [ ] Transfer all images (ensure they are high-resolution)
- [ ] Check for responsiveness on the following media sizes:
   - [ ] Mobile (iPhone SE)
   - [ ] Desktop: 600px < vw < 996px
   - [ ] Desktop: 996px < vw > 1200px
   - [ ] Desktop: vw > 1200px
- [ ] Open a PR for the branch and assign reviewers

## Notes

None

**Comment by dylanvu** [comment]
since this is done, I'll close this to tidy up the issue list
